create extension if not exists pgcrypto;

do $$ begin create type public.subscription_plan as enum ('free','pro'); exception when duplicate_object then null; end $$;
do $$ begin create type public.subscription_status as enum ('inactive','active','past_due','cancelled','expired'); exception when duplicate_object then null; end $$;
do $$ begin create type public.scan_status as enum ('processing','completed','failed'); exception when duplicate_object then null; end $$;
do $$ begin create type public.payment_status as enum ('initialized','pending','successful','failed','cancelled','refunded'); exception when duplicate_object then null; end $$;

create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade, full_name text, email text, avatar_url text, plan public.subscription_plan not null default 'free', subscription_status public.subscription_status not null default 'inactive', is_admin boolean not null default false, free_scans_used integer not null default 0 check (free_scans_used >= 0 and free_scans_used <= 2), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.subscriptions (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, plan public.subscription_plan not null default 'pro', status public.subscription_status not null default 'inactive', paystack_customer_code text, paystack_subscription_code text, paystack_authorization_code text, current_period_start timestamptz, current_period_end timestamptz, scans_limit integer not null default 200 check (scans_limit > 0), scans_used integer not null default 0 check (scans_used >= 0), cancel_at_period_end boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create unique index if not exists subscriptions_one_active_per_user on public.subscriptions(user_id) where status in ('active','past_due');
create table if not exists public.meal_scans (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, image_path text, user_request text, status public.scan_status not null default 'processing', error_message text, detected_foods jsonb, nutrition_summary text, sugar_breakdown jsonb, health_insights jsonb, confidence_score numeric(5,2) check (confidence_score is null or confidence_score between 0 and 100), calories numeric(10,2), carbohydrates numeric(10,2), protein numeric(10,2), fat numeric(10,2), fiber numeric(10,2), sugar numeric(10,2), created_at timestamptz not null default now(), completed_at timestamptz);
create index if not exists meal_scans_user_created_idx on public.meal_scans(user_id,created_at desc);
create table if not exists public.usage_tracking (user_id uuid primary key references auth.users(id) on delete cascade, lifetime_free_scans_used integer not null default 0 check (lifetime_free_scans_used >= 0 and lifetime_free_scans_used <= 2), current_period_start timestamptz, current_period_end timestamptz, monthly_scans_used integer not null default 0 check (monthly_scans_used >= 0), updated_at timestamptz not null default now());
create table if not exists public.payments (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, reference text not null unique, amount_minor bigint not null check (amount_minor > 0), currency text not null default 'USD', status public.payment_status not null default 'initialized', gateway text not null default 'paystack', gateway_transaction_id text, paid_at timestamptz, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.security_logs (id bigint generated always as identity primary key, user_id uuid references auth.users(id) on delete set null, event_type text not null, ip_address inet, user_agent text, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());

create or replace function public.set_updated_at() returns trigger language plpgsql security definer set search_path=public as $$ begin new.updated_at=now(); return new; end; $$;
drop trigger if exists profiles_updated_at on public.profiles; create trigger profiles_updated_at before update on public.profiles for each row execute function public.set_updated_at();
drop trigger if exists subscriptions_updated_at on public.subscriptions; create trigger subscriptions_updated_at before update on public.subscriptions for each row execute function public.set_updated_at();
drop trigger if exists usage_updated_at on public.usage_tracking; create trigger usage_updated_at before update on public.usage_tracking for each row execute function public.set_updated_at();
drop trigger if exists payments_updated_at on public.payments; create trigger payments_updated_at before update on public.payments for each row execute function public.set_updated_at();

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,full_name,email,avatar_url) values(new.id,coalesce(new.raw_user_meta_data->>'full_name',new.raw_user_meta_data->>'name'),new.email,new.raw_user_meta_data->>'avatar_url') on conflict(id) do update set full_name=coalesce(excluded.full_name,profiles.full_name),email=coalesce(excluded.email,profiles.email),avatar_url=coalesce(excluded.avatar_url,profiles.avatar_url); insert into public.usage_tracking(user_id) values(new.id) on conflict(user_id) do nothing; return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users; create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.profiles where id=auth.uid() and is_admin=true); $$;
create or replace function public.get_scan_balance() returns jsonb language plpgsql stable security definer set search_path=public as $$ declare p public.profiles; s public.subscriptions; u public.usage_tracking; begin select * into p from public.profiles where id=auth.uid(); select * into s from public.subscriptions where user_id=auth.uid() and status in('active','past_due') order by current_period_end desc nulls last limit 1; select * into u from public.usage_tracking where user_id=auth.uid(); if p.plan='pro' and s.id is not null then return jsonb_build_object('plan','pro','remaining',greatest(s.scans_limit-s.scans_used,0),'limit',s.scans_limit,'used',s.scans_used,'period_end',s.current_period_end); end if; return jsonb_build_object('plan','free','remaining',greatest(2-coalesce(u.lifetime_free_scans_used,0),0),'limit',2,'used',coalesce(u.lifetime_free_scans_used,0)); end; $$;
create or replace function public.consume_successful_scan_admin(p_user_id uuid,p_scan_id uuid) returns jsonb language plpgsql security definer set search_path=public as $$ declare p public.profiles; s public.subscriptions; u public.usage_tracking; remaining integer; begin select * into p from public.profiles where id=p_user_id for update; select * into u from public.usage_tracking where user_id=p_user_id for update; select * into s from public.subscriptions where user_id=p_user_id and status in('active','past_due') order by current_period_end desc nulls last limit 1 for update; if exists(select 1 from public.meal_scans where id=p_scan_id and user_id=p_user_id and error_message='SCAN_DEDUCTED') then return jsonb_build_object('ok',true,'already_processed',true); end if; if s.id is not null and p.plan='pro' then if s.scans_used>=s.scans_limit then raise exception 'scan_limit_reached'; end if; update public.subscriptions set scans_used=scans_used+1 where id=s.id; update public.usage_tracking set monthly_scans_used=monthly_scans_used+1 where user_id=p_user_id; remaining:=s.scans_limit-s.scans_used-1; else if u.lifetime_free_scans_used>=2 then raise exception 'scan_limit_reached'; end if; update public.usage_tracking set lifetime_free_scans_used=lifetime_free_scans_used+1 where user_id=p_user_id; update public.profiles set free_scans_used=free_scans_used+1 where id=p_user_id; remaining:=2-u.lifetime_free_scans_used-1; end if; update public.meal_scans set error_message='SCAN_DEDUCTED' where id=p_scan_id and user_id=p_user_id; return jsonb_build_object('ok',true,'remaining',remaining); end; $$;
revoke all on function public.consume_successful_scan_admin(uuid,uuid) from public,anon,authenticated; grant execute on function public.consume_successful_scan_admin(uuid,uuid) to service_role;

alter table public.profiles enable row level security; alter table public.subscriptions enable row level security; alter table public.meal_scans enable row level security; alter table public.usage_tracking enable row level security; alter table public.payments enable row level security; alter table public.security_logs enable row level security;
drop policy if exists profiles_select_own on public.profiles; create policy profiles_select_own on public.profiles for select using(id=auth.uid() or public.is_admin());
drop policy if exists profiles_update_own on public.profiles; create policy profiles_update_own on public.profiles for update using(id=auth.uid()) with check(id=auth.uid());
drop policy if exists subscriptions_select_own on public.subscriptions; create policy subscriptions_select_own on public.subscriptions for select using(user_id=auth.uid() or public.is_admin());
drop policy if exists meal_scans_select_own on public.meal_scans; create policy meal_scans_select_own on public.meal_scans for select using(user_id=auth.uid() or public.is_admin());
drop policy if exists meal_scans_delete_own on public.meal_scans; create policy meal_scans_delete_own on public.meal_scans for delete using(user_id=auth.uid());
drop policy if exists usage_select_own on public.usage_tracking; create policy usage_select_own on public.usage_tracking for select using(user_id=auth.uid() or public.is_admin());
drop policy if exists payments_select_own on public.payments; create policy payments_select_own on public.payments for select using(user_id=auth.uid() or public.is_admin());
drop policy if exists security_logs_admin_select on public.security_logs; create policy security_logs_admin_select on public.security_logs for select using(public.is_admin());
insert into storage.buckets(id,name,public) values('meal-images','meal-images',false) on conflict(id) do nothing;
drop policy if exists meal_images_select_own on storage.objects; create policy meal_images_select_own on storage.objects for select to authenticated using(bucket_id='meal-images' and (storage.foldername(name))[1]=auth.uid()::text);
drop policy if exists meal_images_insert_own on storage.objects; create policy meal_images_insert_own on storage.objects for insert to authenticated with check(bucket_id='meal-images' and (storage.foldername(name))[1]=auth.uid()::text);
drop policy if exists meal_images_delete_own on storage.objects; create policy meal_images_delete_own on storage.objects for delete to authenticated using(bucket_id='meal-images' and (storage.foldername(name))[1]=auth.uid()::text);
